module FinalGame
puts "Harry Potter's Secret Adventure"
puts "Welcome to Hogwarts!"
puts "Voldemort has come back to life and is planning on destroying the school"
puts "You are Harry in this game."
puts "Help Harry choose the right spells to defeat Voldemort!"

  puts "Harry is walking down the stairs with Ron and Hermione towards Dining Hall when all of a sudden.."
  puts "Poof!"
  puts "Harry turns his head to see Voldemort"


  puts "What do you want to do?"
  puts "Options: (r)un, (f)ight"
  puts "Enter the letter corresponding to your choice"

  option = gets.chomp
    case option.downcase
    when "r"
      puts "Voldemort: You coward!"
      puts "Voldemort: Crucio!"
      puts "Voldemort casts the unforgivable curse on your best friend, Ron."
      puts "What do you want to do now?"
      puts "Options: (r)un, (f)ight"
      puts "Enter the letter corresponding to your choice."
        answer = gets.chomp
        case answer.downcase
        when "r"
          puts "Ron: Help me Harry!"
          puts "Voldemort: It's too late to be saved now, Harry has made his choice. Let's see how much he cares about Hermione."
          puts "Zap!"
          puts "Hermione is stunned by Voldemort"
          puts "Will you save your friends?"
          puts "Options: (s)ave Ron and Hermione, (a)bandon your best friends"
          puts "Enter the letter corresponding to your choice."
            optionII = gets.chomp
            case optionII.downcase
            when "s"
              puts "Harry Potter: Hermione!! Ron!! Don't worry I will save you."
              puts "Voldemort: Just try."
              puts "Harry Potter: Experillamus!"
              puts "Voldemort's wand flys from his hand"
              puts "The spells are lifted from his friends and Harry kills Voldemort."
              puts "You Won!"
            when "a"
              puts "Voldemort: Well well well. I'm quite surprised Harry. I really expected more from the Boy Who Lived. You shouldn't be too difficult to kill."
              puts "Voldemort: Avada Kedavra!!!"
              puts "Will You Fight or Run?"
              puts "Options: (f)ight or (r)un?"
              puts "Enter the letter corresponding to your choice."
              optionIII = gets.chomp
              case optionIII.downcase
              when "r"
                puts "You Died."
                puts "Game Over..."
              when "f"
                puts "What Spell Do you want to use?"
                puts "Options: (ex)pecto patronum, (e)xperillamus, (s)tupify"
                optionIV = gets.chomp
                case optionIV.downcase
                when "ex"
                  puts "Harry raises his wand"
                  puts "Harry Potter: Expecto Patronum!!!"
                  puts "Harry is struck by Voldemorts curse and falls to his knees"
                  puts "Voldemort: Are you stupid? A Patronus spell only works on Death Eaters"
                  puts "Harry realizes his mistake but it's too late. He is dead."
                  puts "You Lost."
                  puts "Game Over..."
                when "s"
                  puts "Harry raises his wand"
                  puts "Harry Potter: Stupify!!!"
                  puts "A beam of red light flows through Harry's wand."
                  puts "Voldemort easily deflects the spell and kills Harry"
                  puts "Voldemort: Guess you weren't so lucky this time."
                  puts "You Lost."
                  puts "Game Over..."
                when "e"
                  puts "Harry raises his wand"
                  puts "Harry Potter: Experillamus!!!"
                  puts "A beam of green light flows through Harry's wand as he unleashes a powerful spell."
                  puts "Voldemort stumbles and his wand flies from his hand"
                  puts "Voldemort: Ah very good Harry Potter, very good"
                  puts "What will you do next?"
                  puts "Options: (k)ill Voldemort or (c)all the minestry of magic to arrest him"
                    optionV = gets.chomp
                    case optionV.downcase
                    when "k"
                      puts "Harry Potter: Avada Kedavra!"
                      puts "The spell strikes Voldemort and he is dead"
                      puts "Great Job! You saved the Day!"
                    when "c"
                      puts "Harry Potter calls for the Minestry of Magic, but by the time he does that, Voldemort apparates."
                      puts "Voldemort escaped. You failed."
                      puts "Game Over..."
                    end
                end
              end
            end
        when "f"
          puts "Harry Potter: Ron!!"
          puts "Voldemort: That's what happens when you run Harry. I'm tired of your lucky escapes. I have come back to life and you will not stop me this time. I'll make sure of it!"
          puts "Voldemort raises his wand."
          puts "Voldemort: Avada Kedavra!"
          puts "A powerful red beam shoots out of his wand."
          puts "What spell will you choose?"
          puts "Options: (a)vada kedavra, (e)xperillamus, (s)tupify"
            optionVI = gets.chomp
            case optionVI.downcase
            when "s"
              puts "Harry raises his wand"
              puts "Harry Potter: Stupify!!!"
              puts "A beam of red light flows through Harry's wand."
              puts "Voldemort easily deflects the spell and kills Harry"
              puts "Voldemort: Guess you weren't so lucky this time."
              puts "You Lost."
              puts "Game Over..."
            when "a"
              puts "Harry Potter: Avada Kedavra!"
              puts "Harry unleashes his spell emitting a green light from his wand"
              puts "Voldemort eyes widen realizing he is too weak."
              puts "The spell hits Voldemort and he dies"
              puts "YOU ARE A HERO, YOU SAVED THE DAY!"
            when "e"
              puts "Harry Potter: Experillamus!!!"
              puts "A beam of green light flows through Harry's wand as he unleashes a powerful spell."
              puts "Voldemort stumbles and his wand flies from his hand"
              puts "Voldemort: Ah very good Harry Potter, very good"
              puts "What will you do next?"
              puts "Options: (k)ill Voldemort with the unforgivable curse: Avada Kedavra, (s)tun him and wait for the proper authorities to arrive."
                optionVII = gets.chomp
                case optionVII.downcase
                when "s"
                  puts "Harry Potter: Stupify!"
                  puts "Harry hits Voldemort with the spell and Voldemort is stunned."
                  puts "The Minestry of Magic enters through the chamber"
                  puts "Something isn't right."
                  puts "Harry Potter: Ron, Hermione..is that Lucious Malfoy?"
                  puts "Lucious Malfoy removes his hood."
                  puts "Lucious Malfoy: Seize them!"
                  puts "Harry can't believe it, what he actually thought was the Minestry of Magic turns out to be a gang of Death Eaters!"
                  puts "Harry, Hermione, and Ron are stunned both literally and then physically."
                  puts "You Lose..For now."
                  puts "Purchase the upgrade on your account to continue playing."
                when "k"
                  puts "Harry Potter: It's time for you to die forever Voldemort"
                  puts "Voldemort slowly grins"
                  puts "Voldemort: You wouldn't Harry, we have a connection. You know that. Spare me and we can rule the world together."
                  puts "What will you do?"
                  puts "Options: (f)inish what you started and kill Voldemort, (t)eam up with Voldemort and potentially rule the world."
                    optionVIII = gets.chomp
                    case optionVIII.downcase
                    when "f"
                      puts "Harry Potter: Avada Kedavra!!!"
                      puts "Zap! The spell hits Voldemort and he dies."
                      puts "CONGRATS! YOU DID IT"
                      puts "YOU WIN."
                    when "t"
                      puts "Harry Potter: Let's do it buddy."
                      puts "Harry grabs Voldemort's hand and pulls him off the floor."
                      puts "Then they fist bump."
                      puts "Purchase the upgrade on your account to continue playing."
                    else
                      puts "You shouldn't have messed around. Your mistake cost you your life."
                      puts "Voldemort killed you."
                      puts "Game Over."
                    end
                else
                  puts "You shouldn't have messed around. Your mistake cost you your life."
                  puts "Voldemort killed you."
                  puts "Game Over."
                end
            else
              puts "You shouldn't have messed around. Your mistake cost you your life."
              puts "Voldemort killed you."
              puts "Game Over."
            end
        else
          puts "You shouldn't have messed around. Your mistake cost you your life."
          puts "Voldemort killed you."
          puts "Game Over."
        end
    when "f"
      puts "Voldemort: Well, hello Harry Potter."
      puts "Harry Potter: Voldemort."
      puts "Voldemort: Are you ready to finally die?"
      puts "Harry Potter: No are you?"
      puts "Harry and Voldemort both draw wands"
      puts "Voldemort: Avada Kedavra!!!"
      puts "What spell will you choose"
      puts "Options: Avada Kedavra, Experillamus, Stupify"
      puts "Options: (a)vada kedavra, (e)xperillamus, (s)tupify."
      puts "Enter the letter corresponding to your choice"
        optionVII = gets.chomp
        case optionVII.downcase
        when "a"
          puts "Harry Potter: Avada Kedavra!"
          puts "Harry unleashes a powerful spell emitting a green light from his wand"
          puts "Voldemort eyes widen realizing he is too weak."
          puts "The spell hits Voldemort and he dies"
          puts "YOU ARE A HERO, YOU SAVED THE DAY!"
        when "s"
          puts "Harry raises his wand"
          puts "Harry Potter: Stupify!!!"
          puts "A beam of red light flows through Harry's wand."
          puts "Voldemort easily deflects the spell and kills Harry"
          puts "Voldemort: Guess you weren't so lucky this time."
          puts "You Lost."
          puts "Game Over..."
        when "e"
          puts "Harry Potter: Experillamus!!!"
          puts "A beam of green light flows through Harry's wand as he unleashes a powerful spell."
          puts "Voldemort stumbles and his wand flies from his hand"
          puts "Voldemort: Ah very good Harry Potter, very good"
          puts "What will you do next?"
          puts "Options: (k)ill Voldemort with the unforgivable curse: Avada Kedavra, (s)tun him and wait for the proper authorities to arrive."
          optionVII = gets.chomp
          case optionVII.downcase
          when "s"
            puts "Harry Potter: Stupify!"
            puts "Harry hits Voldemort with the spell and Voldemort is stunned."
            puts "The Minestry of Magic enters through the chamber"
            puts "Something isn't right."
            puts "Harry Potter: Ron, Hermione..is that Lucious Malfoy?"
            puts "Lucious Malfoy removes his hood."
            puts "Lucious Malfoy: Seize them!"
            puts "Harry can't believe it, what he actually thought was the Minestry of Magic turns out to be a gang of Death Eaters!"
            puts "Harry, Hermione, and Ron are stunned both literally and then physically."
            puts "You Lose..For now."
            puts "Purchase the upgrade on your account to continue playing."
          when "k"
            puts "Harry Potter: It's time for you to die forever Voldemort"
            puts "Voldemort slowly grins"
            puts "Voldemort: You wouldn't Harry, we have a connection. You know that. Spare me and we can rule the world together."
            puts "What will you do?"
            puts "Options: (f)inish what you started and kill Voldemort, (t)eam up with Voldemort and potentially rule the world."
              optionVIII = gets.chomp
              case optionVIII.downcase
              when "f"
                puts "Harry Potter: Avada Kedavra!!!"
                puts "Zap! The spell hits Voldemort and he dies."
                puts "CONGRATS! YOU DID IT"
                puts "YOU WIN."
              when "t"
                puts "Harry Potter: Let's do it buddy."
                puts "Harry grabs Voldemort's hand and pulls him off the floor."
                puts "Then they fist bump."
                puts "Purchase the upgrade on your account to continue playing."
              else
                puts "You shouldn't have messed around. Your mistake cost you your life."
                puts "Voldemort killed you."
                puts "Game Over."
              end
          else
            puts "You shouldn't have messed around. Your mistake cost you your life."
            puts "Voldemort killed you."
            puts "Game Over."
          end
        else
          puts "You shouldn't have messed around. Your mistake cost you your life."
          puts "Voldemort killed you."
          puts "Game Over."
        end
    else
      puts "You shouldn't have messed around. Your mistake cost you your life."
      puts "Voldemort killed you."
      puts "Game Over."
    end
end
